### ISSUE TITLE
Problem with deploying binary files?

### ISSUE THREAD

**Issue by rschmehl** [exuanbo/actions-deploy-gist#92]
I am using this action to deploy a server-side built PDF to a gist. For some reason, the PDF deposited in the gist is different from the PDF that was built on the github server. The deposited PDF is about twice as large and corrupt. I have narrowed down the problem to the actual file transfer. Is it possible that this action is limited to ASCII files?

**Comment by rschmehl** [comment]
The line in run.ts `const content = await fs.readFile(filePath, 'utf-8')` suggests this...

**Comment by exuanbo** [comment]
I found that posting binary files to Gists via the HTTP API is not supported.

The only workaround seems to be to use git:

```sh
# https://gist.github.com/remarkablemark/feff40b0a522f0c41c4eff0b77ea1d47

# with ssh
git clone git@gist.github.com:<hash>.git gist

# with https
git clone https://gist.github.com/<hash>.git gist

cp BINARY gist

cd gist
git add BINARY
git commit -m "Add BINARY"
git push origin master
```

I will find a way to implement this in the next few days.

**Comment by exuanbo** [comment]
I just released a new patch version, hopefully it will solve the problem :)

**Comment by rschmehl** [comment]
I am still getting this message

``Run exuanbo/actions-deploy-gist@v1.1.3
  Dump inputs
  Deploy to gist
    [INFO] Action failed with "Error: Pushing to https://gist.github.com/3f94046cad52b8cffbe398bc0c61bfcd.git\\
    error: src refspec master does not match any\\
    error: failed to push some refs to 'https://gist.github.com/3f94046cad52b8cffbe398bc0c61bfcd.git'
    "``

**Comment by exuanbo** [comment]
I have released another patch version. This should be fixed now.

**Comment by rschmehl** [comment]
Thanks. I am still getting this error. 

    [INFO] Action failed with "Error: To https://gist.github.com/3f94046cad52b8cffbe398bc0c61bfcd.git
    !	refs/heads/main:refs/heads/main	[remote rejected] (pre-receive hook declined)
    Done
    Pushing to https://gist.github.com/3f94046cad52b8cffbe398bc0c61bfcd.git
    POST git-receive-pack (chunked)
    remote: error: this repository is above its size quota        
    error: failed to push some refs to 'https://gist.github.com/3f94046cad52b8cffbe398bc0c61bfcd.git'

**Comment by exuanbo** [comment]
I can't reproduce the error in your previous (deleted?) comment. Is it working properly now?

**Comment by rschmehl** [comment]
Thanks. Upon closer look, the error in the previous comment (deleted) was due to exceeded quota in the gist repository. The PDF that was deployed by this action is around 15 MB in size and with frequent pushes to the repository and Latex builds the quota was reached. So, entirely unrelated to your code. I will check this later with a new gist and will report here.

**Comment by rschmehl** [comment]
Next thing I found out is that `LFS cannot be used on Gist repositories`. I wanted to use LFS because I am not interested in keeping the deployment history of the binary (and because it is large, which rapidly brings the gist repo to exceeding its quota). Will try now without LFS...

**Comment by rschmehl** [comment]
Yes, it does work now, using the new binary option. Thanks a lot for implementing this.
